version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    environment:
      NODE_ENV: production
      MONGO: infra_mongo_1
    restart: always

networks:
  default:
    name: c214